# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
# Later versions of hugo docker image don't contain git binaries
image: registry.gitlab.com/pages/hugo/hugo_extended:0.58.3

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GITEMAIL: "poornalayam@gmail.com"
  GITNAME: "Swami Guruparananda"
  GHUSER: "poornalayam"
  GHREPO: "poornalayam.github.io.git"

# GitLab private variables
# $GH_TOKEN
# $CF_ZONE_ID
# $CF_AUTH_TOKEN

test:
  script:
  - hugo
  except:
  - master

pages:
  before_script:
# Latest hugo docker images don't contain git or curl
  - apk add --update --no-cache git curl

  script:
# Configure git user
  - git --git-dir public/.git config user.email "$GITEMAIL"
  - git --git-dir public/.git config user.name  "$GITNAME"
  - git --git-dir public/.git checkout master
# Ensure key folders before building
  - rm -rf public/* /tmp/hugo_cache
# Build website in public/ and commit to GitLab
  - hugo --minify
  - git --git-dir public/.git add .
  - git --git-dir public/.git commit -m "rebuilding site `date`"
# Push public/ to to GitHub Pages repo
  - git --git-dir public/.git push https://$GHUSER:$GH_TOKEN@github.com/${GHUSER}/${GHREPO}
# Purge CloudFlare cache, ">-" syntax is needed to bypass processing of special symbols in the curl header
  - >-
      curl
      -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache"
      -H "Authorization: Bearer $CF_AUTH_TOKEN" -H 'Content-Type: application/json'
      --data '{"purge_everything": true}'

  artifacts:
    paths:
    - public

  only:
  - master
