baseurl = "https://www.poornalayam.org/"
title = "Poornalayam (பூர்ணாலயம்)"
description = "Vedanta Talks in Tamil"
theme = "mainroad-custom"
disableKinds = ["home", "sections", "taxonomy", "taxonomyTerm", "RSS"]
googleAnalytics = "UA-632810-7"
enableRobotsTXT = true
assetDir = "static"

[sitemap]
    changefreq = "weekly"
    priority = 0.5
    filename = "sitemap.xml"

[outputs]
  home     = ["HTML"]
  section  = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
    subtitle = "Vedanta Talks in Tamil"

[Params.widgets]
    search = true
    announcements = true
    sitemap = true

[[menu.main]]
    name = "Home"
    url = "/home/"
    identifier = "home"
    weight = 1

[[menu.main]]
    name = "About Swamiji"
    url = "/home/about-swamiji/"
    parent = "home"
    weight = 1

[[menu.main]]
    name = "Classes Recorded"
    url = "/classes-recorded/"
    identifier = "classes-recorded"
    weight = 2

[[menu.main]]
    name = "Books"
    url = "/books/"
    identifier = "books"
    weight = 3

[[menu.main]]
    name = "Contribution"
    url = "/contribution/"
    identifier = "contribution"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    identifier = "contact"
    weight = 5
